name: Build & test
run-name: Build & test — ${{ github.ref_name }}

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Set up project
        uses: ./.github/actions/setup

      - name: Configure project
        run: mkdir build && cd build && cmake ${{github.workspace}} -DBUILD_TESTS=ON -DBUILD_DOCS=OFF -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build project
        run: cmake --build build

      - name: Test project
        run: CTEST_OUTPUT_ON_FAILURE=ON cmake --build ${{github.workspace}}/build --target test
