name: Build

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1.13
      - name: Checkout main
        uses: actions/checkout@v3
      - name: Configure project
        run: cmake -S . -B build -DBUILD_TESTS=OFF -DBUILD_DOCS=OFF
      - name: Build project
        run: cmake --build build
