name: Deploy documentation
run-name: ${{ github.workflow }} — ${{ github.sha }}

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Set up project
        uses: ./.github/actions/setup

      - name: Get Doxygen
        run: sudo apt-get update && sudo apt-get install doxygen -y

      - name: Configure project
        run: mkdir build && cd build && cmake ${{github.workspace}} -DBUILD_TESTS=OFF -DBUILD_DOCS=ON -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build project
        run: cmake --build build --target docs

      - name: Set up pages
        uses: actions/configure-pages@v2

      - name: Upload static files as artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: build/docs/html/

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub pages
        id: deployment
        uses: actions/deploy-pages@v1
