name: Deploy documentation
run-name: ${{ github.workflow }} — ${{ github.sha }}

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  pages: write
  id-token: write

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Set up project
        uses: ./.github/actions/setup

      - name: Update apt
        run: sudo apt-get update

      # @TODO: cache lcov
      - name: Get lcov
        run: sudo apt-get install lcov -y

      # @TODO: cache Doxygen
      - name: Get Doxygen
        run: sudo apt-get install doxygen -y

      - name: Configure project
        run: mkdir build && cd build && cmake ${{github.workspace}} -DBUILD_TESTS=ON -DBUILD_COVERAGE=ON -DBUILD_DOCS=ON -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build project
        run: cmake --build build

      - name: Generate coverage report
        uses: ./.github/actions/coverage

      - name: Generate coverage badge
        uses: ./.github/actions/coverage-badge
        with:
          infofile: build/coverage/total.info

      - name: Build documentation
        run: cmake --build build --target docs

      - name: Copy badges to site
        run: cp -r build/badges build/docs/html

      - name: Set up pages
        uses: actions/configure-pages@v2

      - name: Upload static files as artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: build/docs/html/

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub pages
        id: deployment
        uses: actions/deploy-pages@v1
