name: Deploy documentation

# Run if the Build workflow completes successfully
# or if triggered manually.
on:
  workflow_run:
    workflows: [Build]
    branches: [main]
    types: [completed]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy-docs:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Set up project
        uses: ./.github/actions/setup

      - name: Configure project
        run: mkdir build && cd build && cmake ${{github.workspace}} -DBUILD_TESTS=OFF -DBUILD_DOCS=ON -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build project
        run: cmake --build build --target docs

      - name: Set up pages
        uses: actions/configure-pages@v2

      - name: Upload static files as artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: build/docs/html/

      - name: Deploy to GitHub pages
        uses: actions/deploy-pages@v1
