name: MISRA Compliance

run-name: ${{ github.workflow }} - ${{ github.sha }}

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]
  workflow_dispatch:

env: 
  SUPPRESSED_RULES: "2.7,8.7,12.1,15.5,17.8,21.6"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Update apt
        run: sudo apt-get update

      # @TODO: cache cppcheck
      - name: Get cppcheck
        run: sudo apt-get install cppcheck -y

      - name: Generate cppcheck addon config
        run: 'echo {\"script\": \"misra.py\", \"args\": [\"--suppress-rules ${{ env.SUPPRESSED_RULES }}\"]} > misra.json'

      - name: Perform analysis
        run: cppcheck --error-exitcode=1 --addon=misra.json src -I include
